# Fundamental concepts of tensors

- Introduction to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors and NumPy
- Using @tf.function (speed up a python function)
- Using GPUs and TPUs
- Exercises

In [2]:
# Import tensorflow
import tensorflow as tf


In [3]:
print(tf.__version__)

2.12.0-rc0


In [4]:
# Create tensor with tf.constant()
scalar = tf.constant(4)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [5]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensiones)
scalar.ndim

0

In [6]:
# Create a vector 
vector = tf.constant([5, 5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

In [7]:
# Check the dimensions of the vector
vector.ndim

1

In [8]:
# Create a matrix (a matrix has more than one dimension)
matrix = tf.constant([[5,2], [10,2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  2],
       [10,  2]])>

In [9]:
matrix.ndim

2

In [10]:
# Create a matrix float matrix, specifying the dtype of the matrix
float_matrix = tf.constant([[10., 5.], [5., 2.], [10., 10.]], dtype=tf.float16)
float_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 5.,  2.],
       [10., 10.]], dtype=float16)>

In [11]:
float_matrix.ndim

2

In [12]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3,], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])>

In [13]:
tensor.ndim

3

What we've created so far

- Scalar: a single number
- Vector: a number with direction (e.g. wind speed and direction) or a series of a value
- Matrix: a 2-dimensional array of numbers
- Tensor: an n-dimensional array of numbers

### Creating tensors with `tf.Variable`

In [14]:
# Create the  same tensor with tf.Variable()
tensor_variable = tf.Variable([5,1])
tensor_constant = tf.constant([5,1])
tensor_variable, tensor_constant

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 1])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 1])>)

In [15]:
# Read the tensors
tensor_variable[1], tensor_constant[1]

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [17]:
# Let's change one of the elements of the tensors
tensor_variable[1] = 100

TypeError: 'ResourceVariable' object does not support item assignment

The variable object in tensorflow does not support assignment we need to assign new values using the .assign() method

In [18]:
# Change the variable value using the .assign() method
tensor_variable[1].assign(100)
tensor_variable[1]

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [19]:
# Doing the same but with the constant tensor
tensor_constant[1].assign(100)
tensor_constant

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Error! the tf.constant object does not have the assign() attribute, so we can't change it 

In [34]:
# Create a Tensor with random numbers
# Seed is used for reproducibility
random_tensor_normal_a = tf.random.Generator.from_seed(10)
random_tensor_normal_a = random_tensor_normal_a.normal(shape=(3,4))
random_tensor_normal_a

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.29604465, -0.21134205,  0.01063002,  1.5165398 ],
       [ 0.27305737, -0.29925638, -0.3652325 ,  0.61883307],
       [-1.0130816 ,  0.28291714,  1.2132233 ,  0.46988967]],
      dtype=float32)>

In [35]:
# Create a Tensor with random numbers
# Seed is used for reproducibility
random_tensor_normal_b = tf.random.Generator.from_seed(10)
random_tensor_normal_b = random_tensor_normal_b.normal(shape=(3,4))
random_tensor_normal_b

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.29604465, -0.21134205,  0.01063002,  1.5165398 ],
       [ 0.27305737, -0.29925638, -0.3652325 ,  0.61883307],
       [-1.0130816 ,  0.28291714,  1.2132233 ,  0.46988967]],
      dtype=float32)>

In [36]:
# Are these the same? 
random_tensor_normal_a == random_tensor_normal_b

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])>

These are the same because the seed was set to 42 in both 

In [33]:
# There's also the uniform way
random_tensor_uniform = tf.random.Generator.from_seed(10)
random_tensor_uniform = random_tensor_uniform.uniform(shape=(3,4))
random_tensor_uniform

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.93598676, 0.6513264 , 0.31663585, 0.00111556],
       [0.9212191 , 0.3822806 , 0.77246034, 0.91514194],
       [0.5751133 , 0.793342  , 0.4289763 , 0.19118965]], dtype=float32)>

In [ ]:
# Shuffle the values in the tensors (change the value positions or order)
# It's good practice to shuffle the values while training a Neural Network
normal_tensor = tf.constant([[5, 1]
                                []])