# Fundamental concepts of tensors

- Introduction to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors and NumPy
- Using @tf.function (speed up a python function)
- Using GPUs and TPUs
- Exercises

In [2]:
# Import tensorflow and numpy
import tensorflow as tf
import numpy as np

In [3]:
print(tf.__version__)

2.12.0-rc0


In [4]:
# Create tensor with tf.constant()
scalar = tf.constant(4)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [5]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensiones)
scalar.ndim

0

In [6]:
# Create a vector 
vector = tf.constant([5, 5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

In [7]:
# Check the dimensions of the vector
vector.ndim

1

In [8]:
# Create a matrix (a matrix has more than one dimension)
matrix = tf.constant([[5,2], [10,2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  2],
       [10,  2]])>

In [9]:
matrix.ndim

2

In [10]:
# Create a matrix float matrix, specifying the dtype of the matrix
float_matrix = tf.constant([[10., 5.], [5., 2.], [10., 10.]], dtype=tf.float16)
float_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 5.,  2.],
       [10., 10.]], dtype=float16)>

In [11]:
float_matrix.ndim

2

In [12]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3,], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])>

In [13]:
tensor.ndim

3

What we've created so far

- Scalar: a single number
- Vector: a number with direction (e.g. wind speed and direction) or a series of a value
- Matrix: a 2-dimensional array of numbers
- Tensor: an n-dimensional array of numbers

### Creating tensors with `tf.Variable`

In [14]:
# Create the  same tensor with tf.Variable()
tensor_variable = tf.Variable([5,1])
tensor_constant = tf.constant([5,1])
tensor_variable, tensor_constant

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 1])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 1])>)

In [15]:
# Read the tensors
tensor_variable[1], tensor_constant[1]

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [16]:
# Let's change one of the elements of the tensors
tensor_variable[1] = 100

TypeError: 'ResourceVariable' object does not support item assignment

The variable object in tensorflow does not support assignment we need to assign new values using the .assign() method

In [17]:
# Change the variable value using the .assign() method
tensor_variable[1].assign(100)
tensor_variable[1]

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [18]:
# Doing the same but with the constant tensor
tensor_constant[1].assign(100)
tensor_constant

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Error! the tf.constant object does not have the assign() attribute, so we can't change it 

In [19]:
# Create a Tensor with random numbers
# Seed is used for reproducibility
random_tensor_normal_a = tf.random.Generator.from_seed(10)
random_tensor_normal_a = random_tensor_normal_a.normal(shape=(3,4))
random_tensor_normal_a

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.29604465, -0.21134205,  0.01063002,  1.5165398 ],
       [ 0.27305737, -0.29925638, -0.3652325 ,  0.61883307],
       [-1.0130816 ,  0.28291714,  1.2132233 ,  0.46988967]],
      dtype=float32)>

In [20]:
# Create a Tensor with random numbers
# Seed is used for reproducibility
random_tensor_normal_b = tf.random.Generator.from_seed(10)
random_tensor_normal_b = random_tensor_normal_b.normal(shape=(3,4))
random_tensor_normal_b

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.29604465, -0.21134205,  0.01063002,  1.5165398 ],
       [ 0.27305737, -0.29925638, -0.3652325 ,  0.61883307],
       [-1.0130816 ,  0.28291714,  1.2132233 ,  0.46988967]],
      dtype=float32)>

In [21]:
# Are these the same? 
random_tensor_normal_a == random_tensor_normal_b

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])>

These are the same because the seed was set to 42 in both 

In [22]:
# There's also the uniform way
random_tensor_uniform = tf.random.Generator.from_seed(10)
random_tensor_uniform = random_tensor_uniform.uniform(shape=(3,4))
random_tensor_uniform

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.93598676, 0.6513264 , 0.31663585, 0.00111556],
       [0.9212191 , 0.3822806 , 0.77246034, 0.91514194],
       [0.5751133 , 0.793342  , 0.4289763 , 0.19118965]], dtype=float32)>

In [23]:
# Shuffle the values in the tensors (change the value positions or order)
# It's good practice to shuffle the values while training a Neural Network
normal_tensor = tf.constant([
                        [5, 1],
                        [9, 2],
                        [7, 4]])
tf.random.shuffle(normal_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[7, 4],
       [5, 1],
       [9, 2]])>

In [24]:
# Setting the seed parameter will enable reproducibility
tf.random.set_seed(10)
tf.random.shuffle(normal_tensor, seed=5) 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 1],
       [9, 2],
       [7, 4]])>

There's two seed values, global seed and operation seed, see [tf.random.set_seed()](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)

In [25]:
tf.random.set_seed(10) # Global seed
tf.random.shuffle(normal_tensor, seed=5) # Operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 1],
       [9, 2],
       [7, 4]])>

What if we want to create a simple integer tensor from random numbers between limits

In [26]:
# Create a tensor with random values between two limits
random_tensor_int = tf.constant(np.random.randint(0, 50, size=9))
random_tensor_int

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([32, 23, 25,  5, 30,  5, 10,  8, 33])>

Other way to make tensors, matrices and arrays

In [27]:
# tf.ones() creates a tensor made of only ones as elements
tf.ones([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [28]:
# tf.zeros() creates a tensor made of only zeros as elements
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [29]:
# another way to do it
tf.zeros(shape=(5,2))

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

Numpy arrays can be transformed into tensorflow tensors too

The main difference between a numpy array and a tensorflow tensor is that the later is optimized for GPU numerical operations

In [30]:
numpy_array = np.arange(1,10, dtype=np.int32)
numpy_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# Creating a tensor based on a numpy array
numpy_tensorflow_array = tf.constant(numpy_array)
numpy_tensorflow_array

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [32]:
# Passing more parameters and changing the output
numpy_tensorflow_array = tf.constant(numpy_array, shape=(3,3))
numpy_tensorflow_array

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

# Metadata of tensors
### Getting information about tensors:

- Shape
- Rank
- Axis or dimension
- Size

In [33]:
# Create a rank 5 tensor(5 dimensiones)
rank_5_tensor = tf.zeros(shape=[5,4,2])
rank_5_tensor

<tf.Tensor: shape=(5, 4, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)>

In [34]:
print(f'Using rank_5_tensor: \nType: {rank_5_tensor.dtype}\nNdim: {rank_5_tensor.ndim} \nShape: {rank_5_tensor.shape} \nSize: {tf.size(rank_5_tensor)}')

Using rank_5_tensor: 
Type: <dtype: 'float32'>
Ndim: 3 
Shape: (5, 4, 2) 
Size: 40


In [35]:
# Why size is 40? It's 40 because of the multiplication of ndimensions of the tensor
5 * 4 * 2

40

In [36]:
tf.size(rank_5_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=40>

In [37]:
tf.size(rank_5_tensor).numpy()

40

In [38]:
print(tf.size(rank_5_tensor))

tf.Tensor(40, shape=(), dtype=int32)


In [39]:
print(tf.size(rank_5_tensor).numpy())

40


## Indexing tensors

Tensors can be indexed just like a list or an array

In [40]:
# List example
example_list = [1, 2, 3, 4, 5]
example_list[3]

4

In [41]:
# Get an specific element
rank_5_tensor[1,2,1]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [42]:
# Get the first two elements of each dimension
rank_5_tensor[:2, :2, :2]

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)>

In [43]:
# Get the first element from each dimension from each index
rank_5_tensor[:1, :1, :]

<tf.Tensor: shape=(1, 1, 2), dtype=float32, numpy=array([[[0., 0.]]], dtype=float32)>

In [44]:
# Create a rank two tensor
# rank_2_tensor = tf.zeros(shape=[6,2])
rank_2_tensor = tf.constant([
                            [1, 2], 
                            [3, 4], 
                            [5, 6], 
                            [8, 9], 
                            [200, 0]])
rank_2_tensor.shape, rank_2_tensor.ndim, rank_2_tensor

(TensorShape([5, 2]),
 2,
 <tf.Tensor: shape=(5, 2), dtype=int32, numpy=
 array([[  1,   2],
        [  3,   4],
        [  5,   6],
        [  8,   9],
        [200,   0]])>)

In [45]:
# Get the last item of each of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 4, 6, 9, 0])>

Adding a dimension to a tensor

In [46]:
# Add an extra dimension to the 2 rank tensor
# The [..., 1] the (...), means in all the axis before the last one, equivalent to [:, :, :, :,  ...     1]
rank_3_tensor = rank_2_tensor[..., tf.newaxis] 
rank_3_tensor

<tf.Tensor: shape=(5, 2, 1), dtype=int32, numpy=
array([[[  1],
        [  2]],

       [[  3],
        [  4]],

       [[  5],
        [  6]],

       [[  8],
        [  9]],

       [[200],
        [  0]]])>

In [47]:
# Another way to add a dimension
# The -1 in this example means expand at the last axis
tf.expand_dims(rank_2_tensor, axis=-1) 

<tf.Tensor: shape=(5, 2, 1), dtype=int32, numpy=
array([[[  1],
        [  2]],

       [[  3],
        [  4]],

       [[  5],
        [  6]],

       [[  8],
        [  9]],

       [[200],
        [  0]]])>

In [48]:
# Expanding at the first axis(the 0 axis)
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 5, 2), dtype=int32, numpy=
array([[[  1,   2],
        [  3,   4],
        [  5,   6],
        [  8,   9],
        [200,   0]]])>

### Tensor Operations (manipulating tensors)

Basic operations

`+`, `-`, `*`, `/`

Adding values to a tensor

In [49]:
# Adding values to a tensor
tensor_sum = tf.constant([[1, 2, 3], 
                        [10, 20, 30]])
tensor_sum + 200

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[201, 202, 203],
       [210, 220, 230]])>

In [50]:
tensor_sum - 50

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-49, -48, -47],
       [-40, -30, -20]])>

In [51]:
tensor_sum * 1000

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1000,  2000,  3000],
       [10000, 20000, 30000]])>

In [52]:
tensor_sum / 2

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 0.5,  1. ,  1.5],
       [ 5. , 10. , 15. ]])>

We can use the tensorflow built-in funcion to do these operations and get better performance by leveraging the tensorflow backend

These are: 

- tf.math.add()
- tf.math.substract()
- tf.math.multiply()
- tf.math.divide()

In a hurry we can call these function by their alias like: tf.add(), tf. substract(), etc

In [53]:
# sum
tf.add(tensor_sum, 10)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [20, 30, 40]])>

In [54]:
# substraction
tf.subtract(tensor_sum, 200)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-199, -198, -197],
       [-190, -180, -170]])>

In [55]:
# multiplication
tf.multiply(tensor_sum, 2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [20, 40, 60]])>

In [56]:
# division
tf.divide(tensor_sum, 10)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0.1, 0.2, 0.3],
       [1. , 2. , 3. ]])>

## Matrix multiplication

In machine learning there's a lot of multiplications and is not viable to multiply two large matrices element wise (like with the * operator)

And besides, an element wise multiplication of two matrices isn't the same as the dot product of two matrices

The dot product as another name for matrix multiplication

Multiply two matrices, in order to do so, the first matrix columns must match with the second matrix rows

matrix_a (2,3) and matrix_b (3,4) are compatible, see 

**(*2*, `3`)** & **(`3`, *4*)** making a: 

(2,4) matrix

In [57]:
# Example with a (2,3) . (3,3) making a (2,3) matrix
tf.linalg.matmul(tensor_sum, numpy_tensorflow_array)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 30,  36,  42],
       [300, 360, 420]])>

In [58]:
# Calling matmul by its alias
tf.matmul(tensor_sum, numpy_tensorflow_array)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 30,  36,  42],
       [300, 360, 420]])>

In [59]:
# The function tensordot does the same thing but with more arguments and is more flexible
tf.tensordot(tensor_sum, numpy_tensorflow_array, axes=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 30,  36,  42],
       [300, 360, 420]])>

In [60]:
# checking the variable again
tensor_sum

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [10, 20, 30]])>

In [61]:
# Element wise multiplication
# both matrices must have the same shape 
tf.multiply(tensor_sum, tensor_sum)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  1,   4,   9],
       [100, 400, 900]])>

In [62]:
# Comparing outputs
tf.multiply(tensor_sum, tensor_sum) == tf.matmul(tensor_sum, numpy_tensorflow_array)

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[False, False, False],
       [False, False, False]])>

In [63]:
tensor_sum

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [10, 20, 30]])>

In [64]:
# Chaning matrices shapes, this is useful to make matrices compatible 
# Keep in mind that the order of the elements change
tf.reshape(tensor_sum, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3, 10],
       [20, 30]])>

In [65]:
# There 's also the transpose function, this one transposes the matrix
# Basically the first row becomes the first column, the 2nd row, the second column, and so and so
print('original tensor: ',tensor_sum)
print('transposed tensor: ', tf.transpose(tensor_sum))

original tensor:  tf.Tensor(
[[ 1  2  3]
 [10 20 30]], shape=(2, 3), dtype=int32)
transposed tensor:  tf.Tensor(
[[ 1 10]
 [ 2 20]
 [ 3 30]], shape=(3, 2), dtype=int32)


Change the datatype of a tensor

In [66]:
# Create a new tensor with default datatype 
example_tensor_int = tf.constant([5, 1, 3])
example_tensor_int.dtype

tf.int32

In [67]:
# Create a new tensor with default datatype 
example_tensor = tf.constant([5., 1., 3.])
example_tensor.dtype

tf.float32

Change the tensor datatype from float32 to float16 (reduced precision, 

from a float that uses 32bits of memory to 16bits) using a lower precision datatypem 

makes it so the model uses less memory and train faster



read: [Mixed_Precision](https://www.tensorflow.org/guide/mixed_precision) from the tensorflow documentation

In [68]:
# Change the dtype of a tensor from float32 to float16
example_tensor_16 = tf.cast(example_tensor, dtype=tf.float16)
example_tensor_16

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([5., 1., 3.], dtype=float16)>

In [69]:
# Change the dtype of a tensor from int32 to float32
example_tensor_float32 = tf.cast(example_tensor_int, dtype=tf.float32)
example_tensor_float32

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([5., 1., 3.], dtype=float32)>

## Aggrgating tensors

We can aggregate tensor's data just like any table or numpy array

Get the absolute values of a tensor

In [70]:
negative_tensor = tf.constant([[-10, -20], [-34, 5]])
negative_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-10, -20],
       [-34,   5]])>

In [71]:
# Get the absolute values
absolute_tensor = tf.abs(negative_tensor)
absolute_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [34,  5]])>

Forms of aggregations: 

1. Group by - Technically this is the base aggregation
2. Minimum
3. Maximum
4. Count
5. Sum
6. Mean
7. Variance
8. Standard Deviation or STD


MAX - Maximum value 

In [72]:
# Get the maximum value of a tensor
tf.math.reduce_max(absolute_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=34>

In [73]:
# Get the maximum value of a tensor
tf.reduce_max(absolute_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=34>

MIN - Minimum value

In [74]:
tf.reduce_min(absolute_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

COUNT - Count the values of a tensor

In [75]:
tf.size(absolute_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

SUM - Add every element 

In [76]:
tf.reduce_sum(absolute_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=69>

MEAN - Get the mean or average of the tensor

In [77]:
tf.reduce_mean(absolute_tensor) 

<tf.Tensor: shape=(), dtype=int32, numpy=17>

The output got truncated because the tensor has a datatype of int

In [78]:
69/4

17.25

In [79]:
# Using a float as an input, it outputs 17.25
tf.reduce_mean(tf.cast(absolute_tensor, dtype=tf.float16)) 

<tf.Tensor: shape=(), dtype=float16, numpy=17.25>

VARIANCE - Get the variance of a tensor

In [80]:
# Get the variance of the tensor, this function it does not have an alias, it must be called 
# using tf.math.reduce_variance() with a real or complex input tensor
tf.math.reduce_variance(tf.cast(absolute_tensor, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=122.6875>

STD - Get the standard deviation

In [81]:
# Get the variance of the tensor, this function it does not have an alias, it must be called 
# using tf.math.reduce_variance() with a real or complex input tensor
tf.math.reduce_std(tf.cast(absolute_tensor, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=11.076439>