# Fundamental concepts of tensors

- Introduction to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors and NumPy
- Using @tf.function (speed up a python function)
- Using GPUs and TPUs
- Exercises

In [ ]:
# Import tensorflow
import tensorflow as tf


In [ ]:
print(tf.__version__)

2.12.0


In [ ]:
# Create tensor with tf.constant()
scalar = tf.constant(4)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensiones)
scalar.ndim

0

In [ ]:
# Create a vector 
vector = tf.constant([5, 5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

In [ ]:
# Check the dimensions of the vector
vector.ndim

1

In [ ]:
# Create a matrix (a matrix has more than one dimension)
matrix = tf.constant([[5,2], [10,2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 2],
 [10, 2]])>

In [ ]:
matrix.ndim

2

In [ ]:
# Create a matrix float matrix, specifying the dtype of the matrix
float_matrix = tf.constant([[10., 5.], [5., 2.], [10., 10.]], dtype=tf.float16)
float_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 5.],
 [ 5., 2.],
 [10., 10.]], dtype=float16)>

In [ ]:
float_matrix.ndim

2

In [ ]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3,], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1, 2, 3],
 [ 4, 5, 6],
 [ 7, 8, 9]],

 [[10, 11, 12],
 [13, 14, 15],
 [16, 17, 18]]])>

In [ ]:
tensor.ndim

3

What we've created so far

- Scalar: a single number
- Vector: a number with direction (e.g. wind speed and direction) or a series of a value
- Matrix: a 2-dimensional array of numbers
- Tensor: an n-dimensional array of numbers

### Creating tensors with `tf.Variable`

In [4]:
# Create the  same tensor with tf.Variable()
tensor_variable = tf.Variable([5,1])
tensor_constant = tf.constant([5,1])
tensor_variable, tensor_constant

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 1])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 1])>)

In [5]:
# Read the tensors
tensor_variable[1], tensor_constant[1]

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [6]:
# Let's change one of the elements of the tensors
tensor_variable[1] = 100

TypeError: 'ResourceVariable' object does not support item assignment

The variable object in tensorflow does not support assignment we need to assign new values using the .assign() method

In [7]:
# Change the variable value using the .assign() method
tensor_variable[1].assign(100)
tensor_variable[1]

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [9]:
# Doing the same but with the constant tensor
tensor_constant[1].assign(100)
tensor_constant

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Error! the tf.constant object does not have the assign() attribute, so we can't change it 

In [ ]:
# Create a Tensor with random numbers